import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";

import Navbar from "$/Navbar/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <section>
          <div className="container is-fluid">
            <Navbar />
          </div>
        </section>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
