import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import NavbarContext from "@/components/Navbar/NavbarContext";
import PlayStation from "@/components/Scenes/PlayStation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppRouterCacheProvider>
          <div className="background-scene">
            <PlayStation/>
          </div>
          <NavbarContext>{children}</NavbarContext>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
