import "@/app/globals.css";
import ActiveSectionContext from "@/components/UI/ActiveSectionContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          <ActiveSectionContext>{children}</ActiveSectionContext>
      </body>
    </html>
  );
}
