import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import "@/app/globals.css";
import NavbarContext from "@/components/Navbar/NavbarContext";

// Preload Spline scene before scripts load
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  links: [
    {
      rel: "preload",
      href: "https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode",
      as: "fetch",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <NavbarContext>{children}</NavbarContext>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
